[2024-07-10T01:10:55.551+0000] {processor.py:161} INFO - Started process (PID=23084) to work on /opt/airflow/dags/ny_tlc_drivers.py
[2024-07-10T01:10:55.575+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/ny_tlc_drivers.py for tasks to queue
[2024-07-10T01:10:55.694+0000] {logging_mixin.py:188} INFO - [2024-07-10T01:10:55.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/ny_tlc_drivers.py
[2024-07-10T01:10:56.560+0000] {logging_mixin.py:188} INFO - [2024-07-10T01:10:56.226+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/ny_tlc_drivers.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/ny_tlc_drivers.py", line 2, in <module>
    from extract import extract_data
  File "/opt/airflow/dags/extract.py", line 3, in <module>
    from sodapy import Socrata
ModuleNotFoundError: No module named 'sodapy'
[2024-07-10T01:10:56.572+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/ny_tlc_drivers.py
[2024-07-10T01:10:58.428+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/ny_tlc_drivers.py took 3.084 seconds
